version: "3.8"

volumes:
  go_plugins:
  go_src:
  go_pkg:
  go_build_cache:

services:
  teapot:
    build: teapot

  kong:
    image: kong:2.8.1
    depends_on:
      teapot:
        condition: service_started
      go-plugins:
          condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: '0.15'
          # memory: 1G
    logging:
      driver: "json-file" 
      options:
        max-size: "50m"
        max-file: "2"
    environment:
      KONG_LOG_LEVEL: info
      KONG_PROXY_ACCESS_LOG: "off"  #/dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8080 reuseport backlog=163840
      KONG_PORT_MAPS: "80:8080"
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml

      KONG_PLUGINSERVER_NAMES: goplugin

      KONG_PLUGINSERVER_GOPLUGIN_START_CMD: /go-plugins/goplugin -kong-prefix /usr/local/kong/
      KONG_PLUGINSERVER_GOPLUGIN_QUERY_CMD: /go-plugins/goplugin -dump
      KONG_PLUGINSERVER_GOPLUGIN_SOCKET: /usr/local/kong/goplugin.socket

      KONG_PLUGINS: bundled, goplugin

    volumes:
      - ./kong.yml:/kong.yml
      - go_plugins:/go-plugins

    ports:
      - 80:8080
      # - 443:8443
    healthcheck:
      test: kong health
      interval: 10s
      timeout: 2s
      retries: 10

  go-plugins:
    build: go-plugins
    volumes:
      - ./go-plugins/entrypoint.sh:/entrypoint.sh
      - ./go-plugins:/src
      - go_plugins:/go-plugins
      # cache
      - go_src:/go/src
      - go_pkg:/go/pkg
      - go_build_cache:/root/.cache/go-build
